import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";
import { validateEmail, validateUuid } from "@/lib/validation";

export async function POST(request: Request) {
  const supabase = await createClient();
  const { email, role, orgId } = await request.json();

  if (!email || !validateEmail(email)) {
    return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
  }
  if (!orgId || !validateUuid(orgId)) {
    return NextResponse.json({ error: "Invalid organization ID" }, { status: 400 });
  }

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Verify caller is admin
  const { data: membership } = await supabase
    .from("organization_memberships")
    .select("role")
    .eq("user_id", user.id)
    .eq("organization_id", orgId)
    .single();

  if (membership?.role !== "admin") {
    return NextResponse.json({ error: "Only admins can invite" }, { status: 403 });
  }

  // Get the default venture
  const { data: venture } = await supabase
    .from("ventures")
    .select("id")
    .eq("organization_id", orgId)
    .limit(1)
    .single();

  if (!venture) {
    return NextResponse.json({ error: "No venture found" }, { status: 400 });
  }

  // Create invite
  const { data: invite, error } = await supabase
    .from("invites")
    .insert({
      organization_id: orgId,
      venture_id: venture.id,
      email,
      role,
      invited_by: user.id,
    })
    .select()
    .single();

  if (error) {
    console.error("Failed to create invite:", error.message);
    return NextResponse.json({ error: "Failed to create invite" }, { status: 400 });
  }

  // The invite token is auto-generated by the DB default.
  // In production, send an email with a link to /invite/[token].
  // For now, the invite is created and the user can share the link manually.

  return NextResponse.json({
    success: true,
    inviteUrl: `/invite/${invite.token}`,
  });
}
