import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/service";
import { verifyHermesSecret } from "@/lib/hermes/verify-secret";

export const dynamic = "force-dynamic";

/**
 * POST /api/hermes/skills/sync
 *
 * Hermes VPS reports skills from the filesystem.
 * Auto-generated skills arrive with approved=false.
 * Manually synced skills (from VPS skills/ dir) arrive with source='vps_sync'.
 *
 * Body: {
 *   orgId: string,
 *   skills: Array<{
 *     agent_profile: string,
 *     skill_name: string,
 *     skill_description?: string,
 *     skill_content: string,
 *     auto_generated?: boolean,
 *     source?: 'vps_sync' | 'auto_generated'
 *   }>
 * }
 */
export async function POST(request: Request) {
  if (!verifyHermesSecret(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { orgId, skills } = await request.json();

  if (!orgId || !Array.isArray(skills)) {
    return NextResponse.json(
      { error: "Missing required fields: orgId, skills[]" },
      { status: 400 }
    );
  }

  const supabase = createServiceClient();
  let synced = 0;
  let created = 0;

  for (const skill of skills) {
    if (!skill.agent_profile || !skill.skill_name || !skill.skill_content) continue;

    const isAutoGenerated = skill.auto_generated ?? skill.source === "auto_generated";
    const source = skill.source ?? (isAutoGenerated ? "auto_generated" : "vps_sync");

    // Check if skill exists
    const { data: existing } = await supabase
      .from("agent_skills")
      .select("id, skill_content, approved")
      .eq("organization_id", orgId)
      .eq("agent_profile", skill.agent_profile)
      .eq("skill_name", skill.skill_name)
      .single();

    if (existing) {
      // Only update if content changed — don't reset approval for unchanged skills
      if (existing.skill_content !== skill.skill_content) {
        await supabase
          .from("agent_skills")
          .update({
            skill_content: skill.skill_content,
            skill_description: skill.skill_description ?? null,
            source,
            // Reset approval if auto-generated content changed
            ...(isAutoGenerated && existing.approved
              ? { approved: false, approved_by: null, approved_at: null }
              : {}),
          })
          .eq("id", existing.id);
      }
      synced++;
    } else {
      await supabase.from("agent_skills").insert({
        organization_id: orgId,
        agent_profile: skill.agent_profile,
        skill_name: skill.skill_name,
        skill_description: skill.skill_description ?? null,
        skill_content: skill.skill_content,
        auto_generated: isAutoGenerated,
        approved: false,
        source,
      });
      created++;
      synced++;
    }
  }

  return NextResponse.json({ success: true, synced, created });
}
